const dummyEvents = [
  {
    id: 1,
    name: "React Conference 2025",
    description: "A conference about React and frontend development.",
    location: "New York",
    startDate: "2025-08-10 09:00",
    endDate: "2025-08-10 17:00",
    organizer: "John Doe",
    type: "Online",
    maxAttendees: 200,
    tags: ["React", "Frontend", "JavaScript"],
  },
  {
    id: 2,
    name: "Marketing Strategies 101",
    description: "Learn the latest marketing trends.",
    location: "Los Angeles",
    startDate: "2025-09-05 10:00",
    endDate: "2025-09-05 15:00",
    organizer: "Jane Smith",
    type: "Offline",
    maxAttendees: 150,
    tags: ["Marketing", "SEO", "Business"],
  },
  {
    id: 3,
    name: "AI & Machine Learning Summit",
    description: "Discussing the future of AI and ML in various industries.",
    location: "San Francisco",
    startDate: "2025-07-25 09:30",
    endDate: "2025-07-25 18:00",
    organizer: "Michael Johnson",
    type: "Online",
    maxAttendees: 300,
    tags: ["AI", "Machine Learning", "Technology"],
  },
  {
    id: 4,
    name: "Health & Wellness Workshop",
    description: "A holistic approach to mental and physical wellness.",
    location: "Chicago",
    startDate: "2025-10-02 11:00",
    endDate: "2025-10-02 16:00",
    organizer: "Emily Brown",
    type: "Offline",
    maxAttendees: 100,
    tags: ["Health", "Wellness", "Lifestyle"],
  },
  {
    id: 5,
    name: "Next-Gen Startups Pitch Day",
    description: "Networking and pitching for emerging startups.",
    location: "Boston",
    startDate: "2025-11-12 13:00",
    endDate: "2025-11-12 18:00",
    organizer: "Startup Hub Inc.",
    type: "Offline",
    maxAttendees: 250,
    tags: ["Startups", "Entrepreneurship", "Innovation"],
  },
];

export default dummyEvents;
